#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CERT_DIR="${SCRIPT_DIR}/../registry/certs"
mkdir -p "$CERT_DIR"

openssl req -newkey rsa:2048 -nodes -sha256 \
  -keyout "${CERT_DIR}/auth.key" \
  -x509 -days 3650 \
  -out "${CERT_DIR}/auth.crt" \
  -subj "/CN=private-registry-auth"

chmod 600 "${CERT_DIR}/auth.key"
chmod 644 "${CERT_DIR}/auth.crt"

echo "Generated:"
echo "  ${CERT_DIR}/auth.key"
echo "  ${CERT_DIR}/auth.crt"
echo ""
echo "Note: jwks.json will be generated by the API server on startup."
